version: "3.8"

services:
  database:
    container_name: admin-database
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=postgres
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=500"]
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    name: backend
