version: "3.8"

services:
  web:
    build: .
    image: django
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    container_name: web
    volumes:
      - ./:/code/
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - backend

  database:
    container_name: database
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=postgres
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=500"]
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    name: backend
