# Generated by Django 4.1.6 on 2023-02-12 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('scientific_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tree',
                'verbose_name_plural': 'Trees',
                'db_table': 'tree',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantedTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('age', models.IntegerField()),
                ('planted_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.DecimalField(decimal_places=2, max_digits=5)),
                ('account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('tree', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tree_everywhere.tree')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PlantedTree',
                'verbose_name_plural': 'PlantedTree',
                'db_table': 'planted_tree',
                'managed': True,
            },
        ),
    ]
