# Generated by Django 4.1.6 on 2023-02-11 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree_everywhere', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tree',
            table=None,
        ),
    ]
