# Generated by Django 4.1.6 on 2023-02-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_everywhere', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantedtree',
            old_name='location',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='plantedtree',
            name='longitude',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
            preserve_default=False,
        ),
    ]
