# Generated by Django 4.1.6 on 2023-02-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_everywhere', '0003_alter_plantedtree_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantedtree',
            name='latitude',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plantedtree',
            name='longitude',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
