# Generated by Django 4.1.6 on 2023-02-15 19:10

from django.db import migrations

from app.tree_everywhere.models import Tree


def add_trees(apps, schema_editor):
    Tree.objects.bulk_create([
        Tree(name="Aguaí", scientific_name="Chrysophyllum marginatum"),
        Tree(name="Agulheiro", scientific_name="Seguieria langsdorfii"),
        Tree(name="Albízia", scientific_name="Albizia polycephala"),
        Tree(name="Aldrago-miúdo", scientific_name="Pterocarpus rohrii")
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('tree_everywhere', '0004_alter_plantedtree_latitude_and_more'),
    ]

    operations = [
        migrations.RunPython(add_trees)
    ]
