# Generated by Django 4.1.6 on 2023-02-11 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree_everywhere', '0004_plantedtree'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantedtree',
            options={'managed': True, 'verbose_name': 'PlantedTree', 'verbose_name_plural': 'PlantedTree'},
        ),
        migrations.AlterModelTable(
            name='plantedtree',
            table='planted_tree',
        ),
    ]
