# Generated by Django 4.1.6 on 2023-02-11 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tree_everywhere', '0005_alter_plantedtree_options_alter_plantedtree_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantedtree',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
        migrations.AlterField(
            model_name='plantedtree',
            name='tree',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tree_everywhere.tree'),
        ),
        migrations.AlterField(
            model_name='plantedtree',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
