# Generated by Django 4.1.6 on 2023-02-12 02:46

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations

from setup.config import get_config

config_app = get_config()


def add_user(apps, schema_editor):
    user = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    user.objects.create(
        first_name='Admin',
        password=make_password(config_app.ADMIN_PASS),
        username='admin',
        is_superuser=True,
        is_staff=True
    )


def remove_user(apps, schema_editor):
    user = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    user.objects.get(email='admin@youshop.com').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_user, remove_user),
    ]

