# Generated by Django 4.1.6 on 2023-02-11 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'managed': True, 'verbose_name': 'Account', 'verbose_name_plural': 'Account'},
        ),
    ]
