# Generated by Django 4.1.6 on 2023-02-12 15:26

from django.db import migrations
from django.shortcuts import get_object_or_404

from app.account.models import Account, CustomUser


def add_user_to_account(apps, schema_editor):
    account = Account(name='default', active=True)
    account.save()

    user = get_object_or_404(CustomUser.objects.filter(username='admin'))
    account.users.add(user)


def remove_account(apps, schema_editor):
    account = Account.objects.filter(name='default')
    account.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0004_alter_customuser_is_staff'),
    ]

    operations = [
        # migrations.RunPython(add_user_to_account)
    ]
