# Generated by Django 4.1.6 on 2023-02-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_add_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accounts',
            field=models.ManyToManyField(to='account.account'),
        ),
    ]
