# Generated by Django 4.1.6 on 2023-02-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_customuser_accounts_useraccounts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccounts',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='accounts',
        ),
    ]
