# Generated by Django 4.1.6 on 2023-02-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_useraccounts_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccounts',
            old_name='user',
            new_name='custom_user',
        ),
    ]
