# Generated by Django 4.1.6 on 2023-02-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_rename_user_useraccounts_custom_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccounts',
            old_name='custom_user',
            new_name='user',
        ),
    ]
