# Generated by Django 4.1.6 on 2023-02-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_custom_user_useraccounts_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAccounts',
            new_name='UserAccount',
        ),
        migrations.AlterModelTable(
            name='useraccount',
            table='user_account',
        ),
    ]
