# Generated by Django 4.1.6 on 2023-02-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_customuser_accounts_alter_useraccount_account_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useraccount',
            unique_together={('user', 'account')},
        ),
    ]
