# Generated by Django 4.1.6 on 2023-02-13 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_useraccount_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_accounts', to='account.account'),
        ),
    ]
